#!/bin/bash
sbatch batch_files/thick100.sbatch
sbatch batch_files/thick200.sbatch
sbatch batch_files/thick300.sbatch
sbatch batch_files/thick500.sbatch
sbatch batch_files/thick600.sbatch
sbatch batch_files/thick700.sbatch
sbatch batch_files/thick800.sbatch
sbatch batch_files/d45000.sbatch
sbatch batch_files/d67500.sbatch
sbatch batch_files/d112500.sbatch
sbatch batch_files/d120000.sbatch
sbatch batch_files/d45000_constBeta.sbatch
sbatch batch_files/d67500_constBeta.sbatch
sbatch batch_files/d112500_constBeta.sbatch
sbatch batch_files/d120000_constBeta.sbatch
sbatch batch_files/s2v02.sbatch
sbatch batch_files/s2v1.sbatch
sbatch batch_files/s2v2.sbatch
sbatch batch_files/s2v4.sbatch
sbatch batch_files/s2v5.sbatch
sbatch batch_files/s2v6.sbatch
sbatch batch_files/betaNrn_165.sbatch
sbatch batch_files/betaNrn_315.sbatch
sbatch batch_files/betaNrn_39.sbatch
sbatch batch_files/betaNrn_465.sbatch
sbatch batch_files/betaNrn_54.sbatch